### ISSUE TITLE
Sintesis

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-bg55-a#1]
[Sintesis calidad de un proyecto de software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-bg55-a/files/9569260/Sintesis.calidad.de.un.proyecto.de.software.pdf)

**Comment by Lizzetee** [comment]
Calificación: 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado
