### ISSUE TITLE
sintesis

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-bg55-a#2]
[Sintesis calidad de un proyecto de software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-bg55-a/files/12677379/Sintesis.calidad.de.un.proyecto.de.software.pdf)

**Comment by JoseABCruz** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
